=== fercalonso/sew/F1Desktop/xml/circuito.dtd
<!ELEMENT circuito (nombre, caracteristicas, referencias, fotografias, videos, coordenadas, puntos_circuito)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT caracteristicas (dato+)>
<!ELEMENT dato (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>

<!ELEMENT fotografias (fotografia+)>
<!ELEMENT videos (video*)>

<!ELEMENT fotografia (title, altText)>
<!ATTLIST fotografia
    referencia CDATA #REQUIRED>

<!ELEMENT video (title, format)>
<!ATTLIST video
    referencia CDATA #REQUIRED>

<!ELEMENT title (#PCDATA)>
<!ELEMENT altText (#PCDATA)>
<!ELEMENT format (#PCDATA)>

<!ELEMENT coordenadas (longitud, latitud, altitud)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>

<!ELEMENT puntos_circuito (punto+)>
<!ELEMENT punto (distancia_del_tramo, coordenadas, numero_sector, descripcion)>
<!ELEMENT distancia_del_tramo (valor,unidades)>
<!ELEMENT valor (#PCDATA)>
<!ELEMENT unidades (#PCDATA)>
<!ELEMENT numero_sector (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

<!ATTLIST dato 
    valor CDATA #REQUIRED>
<!ATTLIST referencia
    enlace  CDATA #REQUIRED>
<!ATTLIST referencia
    enlace  CDATA #REQUIRED>

<!ATTLIST longitud 
    valor CDATA #REQUIRED>
<!ATTLIST latitud 
    valor CDATA #REQUIRED>
<!ATTLIST altitud 
    valor CDATA #REQUIRED>

=== fercalonso/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE circuito SYSTEM "circuito.dtd">
    <circuito>
        <nombre>Circuito de Monaco</nombre>
        <caracteristicas>
            <dato valor="3,4"> Longitud </dato>
            <dato valor="8,7"> Anchura media </dato>
            <dato valor="26 Mayo"> Fecha </dato>
            <dato valor="15:00"> Hora Espa√±a </dato>
            <dato valor="78"> Vueltas </dato>
            <dato valor="Montecarlo"> Localidad </dato>
            <dato valor="Monaco"> Pais </dato>
        </caracteristicas>
        <referencias>
            <referencia enlace="https://www.dazn.com/es-ES/news/motor/circuito-de-montecarlo-donde-esta-como-es-caracteristicas-como-llegar-y-fotos-del-escenario-del-gp-monaco-del-mundial-de-f1/c79nbs8ayvi41703gx79axz35">Articulo DAZN</referencia>
            <referencia enlace="https://www.f1enestadopuro.com/previo-gran-premio-de-formula-1-monaco-datos-tecnicos-3/">Articulo F1 En Estado Puro</referencia>
            <referencia enlace="https://lat.motorsport.com/f1/news/datos-y-cifras-del-gp-de-monaco-en-monte-carlo-1040839/3100214/"> Articulo Motorsport </referencia>
        </referencias>

        <fotografias>
            <fotografia referencia="xml/imagenes/CircuitoCurva.png">
                <title>Curva del circuito de monaco</title>
                <altText>Famosa curva del circuito de monaco</altText>
            </fotografia>

            <fotografia referencia="xml/imagenes/CircuitoMapa.png">
                <title>Mapa del circuito</title>
                <altText>Mapa con los sectores del circuito destacados</altText>
            </fotografia>
        </fotografias>

        <videos>

        </videos>

        <coordenadas>
            <longitud valor="7.421618619285261"></longitud>
            <latitud valor="43.735981656832294"></latitud>
            <altitud valor="559 m"></altitud>
        </coordenadas>


        <puntos_circuito>

            <punto>
                <distancia_del_tramo>
                    <valor>370</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.421618619285261"></longitud>
                    <latitud valor="43.73700379827298"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 1 </numero_sector>

                <descripcion>
                    Sainte Devote
                </descripcion>
            </punto>


            <punto>
                <distancia_del_tramo>
                    <valor>510</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.424904384331927"></longitud>
                    <latitud valor="43.73747427657312"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 1 </numero_sector>

                <descripcion>
                    Beau Rivage
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>630</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.427692821787937"></longitud>
                    <latitud valor="43.73824749933481"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 1 </numero_sector>

                <descripcion>
                    Massenet
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>791</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.427346572502073"></longitud>
                    <latitud valor="43.739519764458386"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 1 </numero_sector>

                <descripcion>
                    Casino
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>881</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.428810712547052"></longitud>
                    <latitud valor="43.74111363150211"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Mirabeau Haute
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>1015</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.429621925227156"></longitud>
                    <latitud valor="43.74024165569586"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Grand Hotel Hairpin
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>1201</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.429493318338847"></longitud>
                    <latitud valor="43.74095639090184"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Mirabeau Bas
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>1243</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.430324316694077"></longitud>
                    <latitud valor="43.74106360044682"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Portier
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>1721</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.428721677008991"></longitud>
                    <latitud valor="43.7381760229898"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Tunnel
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>2191</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.425516397545511"></longitud>
                    <latitud valor="43.737246822372846"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Nouvelle Chicane
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>2209</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.426456217113925"></longitud>
                    <latitud valor="43.737704276767936"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Nouvelle Chicane End
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>2578</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.422222082518584"></longitud>
                    <latitud valor="43.73677506885242"></latitud>
                    <altitud valor="559"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Tabac
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>2787</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.421816476138738"></longitud>
                    <latitud valor="43.73548130151215"></latitud>
                    <altitud valor="559"></altitud>
