=== fercalonso/sew/F1Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">	
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="caracteristicas" />
				<xs:element ref="referencias" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="coordenadas" />
				<xs:element ref="puntos_circuito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="caracteristicas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="dato" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="dato">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="valor" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="enlace" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" />
				<xs:element ref="altText" />
			</xs:sequence>
			<xs:attribute name="referencia" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title" />
				<xs:element ref="format" />
			</xs:sequence>
			<xs:attribute name="referencia" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="title" type="xs:string" />
	<xs:element name="altText" type="xs:string" />
	<xs:element name="format" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="valor" type="longitudType" use="required" />
				</xs:extension>
				
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="latitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="valor" type="latitudeType" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="altitud">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="valor" type="altitudType" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="latitudeType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-90"/>  
			<xs:maxInclusive value="90"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="longitudType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-180"/> 
			<xs:maxInclusive value="180"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="altitudType">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="-50"/> 
			<xs:maxInclusive value="5000"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="puntos_circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distancia_del_tramo" />
				<xs:element ref="coordenadas" />
				<xs:element ref="numero_sector" />
				<xs:element ref="descripcion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distancia_del_tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="valor" />
				<xs:element ref="unidades" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="valor" type="xs:integer" />
	<xs:element name="unidades" type="xs:string" />
	<xs:element name="numero_sector" type="xs:integer" />
	<xs:element name="descripcion" type="xs:string" />
</xs:schema>

=== fercalonso/sew/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
    <circuito  xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es circuito.xsd " >
        <nombre>Circuito de Monaco</nombre>
        <caracteristicas>
            <dato valor="3,4"> Longitud </dato>
            <dato valor="8,7"> Anchura media </dato>
            <dato valor="26 Mayo"> Fecha </dato>
            <dato valor="15:00"> Hora Espa√±a </dato>
            <dato valor="78"> Vueltas </dato>
            <dato valor="Montecarlo"> Localidad </dato>
            <dato valor="Monaco"> Pais </dato>
        </caracteristicas>
        <referencias>
            <referencia enlace="https://www.dazn.com/es-ES/news/motor/circuito-de-montecarlo-donde-esta-como-es-caracteristicas-como-llegar-y-fotos-del-escenario-del-gp-monaco-del-mundial-de-f1/c79nbs8ayvi41703gx79axz35">Articulo DAZN</referencia>
            <referencia enlace="https://www.f1enestadopuro.com/previo-gran-premio-de-formula-1-monaco-datos-tecnicos-3/">Articulo F1 En Estado Puro</referencia>
            <referencia enlace="https://lat.motorsport.com/f1/news/datos-y-cifras-del-gp-de-monaco-en-monte-carlo-1040839/3100214/"> Articulo Motorsport </referencia>
        </referencias>

        <fotografias>
            <fotografia referencia="xml/imagenes/CircuitoCurva.png">
                <title>Curva del circuito de monaco</title>
                <altText>Famosa curva del circuito de monaco</altText>
            </fotografia>

            <fotografia referencia="xml/imagenes/CircuitoMapa.png">
                <title>Mapa del circuito</title>
                <altText>Mapa con los sectores del circuito destacados</altText>
            </fotografia>
        </fotografias>

        <videos>

        </videos>

        <coordenadas>
            <longitud valor="7.421618619285261"></longitud>
            <latitud valor="43.735981656832294"></latitud>
            <altitud valor="12.54"></altitud>
        </coordenadas>


        <puntos_circuito>

            <punto>
                <distancia_del_tramo>
                    <valor>0</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.4212327986237625"></longitud>
                    <latitud valor="43.735288306165586"></latitud>
                    <altitud valor="4.54"></altitud>
                </coordenadas>

                <numero_sector> 1 </numero_sector>

                <descripcion>
                    Start
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>190</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.421618619285261"></longitud>
                    <latitud valor="43.73700379827298"></latitud>
                    <altitud valor="7.66"></altitud>
                </coordenadas>

                <numero_sector> 1 </numero_sector>

                <descripcion>
                    Sainte Devote
                </descripcion>
            </punto>


            <punto>
                <distancia_del_tramo>
                    <valor>460</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.424904384331927"></longitud>
                    <latitud valor="43.73747427657312"></latitud>
                    <altitud valor="28.89"></altitud>
                </coordenadas>

                <numero_sector> 1 </numero_sector>

                <descripcion>
                    Beau Rivage
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>707</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.427692821787937"></longitud>
                    <latitud valor="43.73824749933481"></latitud>
                    <altitud valor="40.56"></altitud>
                </coordenadas>

                <numero_sector> 1 </numero_sector>

                <descripcion>
                    Massenet
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>856</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.427346572502073"></longitud>
                    <latitud valor="43.739519764458386"></latitud>
                    <altitud valor="42.99"></altitud>
                </coordenadas>

                <numero_sector> 1 </numero_sector>

                <descripcion>
                    Casino
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>1081</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.428810712547052"></longitud>
                    <latitud valor="43.74111363150211"></latitud>
                    <altitud valor="29.87"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Mirabeau Haute
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>1210</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.429621925227156"></longitud>
                    <latitud valor="43.74024165569586"></latitud>
                    <altitud valor="20.67"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Grand Hotel Hairpin
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>1292</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.429493318338847"></longitud>
                    <latitud valor="43.74095639090184"></latitud>
                    <altitud valor="13.88"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Mirabeau Bas
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>1374</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.430324316694077"></longitud>
                    <latitud valor="43.74106360044682"></latitud>
                    <altitud valor="8.56"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Portier
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>1740</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.428721677008991"></longitud>
                    <latitud valor="43.7381760229898"></latitud>
                    <altitud valor="14.56"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Tunnel
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>1934</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.4264643"></longitud>
                    <latitud valor="43.7375104"></latitud>
                    <altitud valor="3.46"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Nouvelle Chicane
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>1987</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.4259433"></longitud>
                    <latitud valor="43.7372918"></latitud>
                    <altitud valor="3.14"></altitud>
                </coordenadas>

                <numero_sector> 2 </numero_sector>

                <descripcion>
                    Nouvelle Chicane End
                </descripcion>
            </punto>

            <punto>
                <distancia_del_tramo>
                    <valor>2293</valor>
                    <unidades>m</unidades>
                </distancia_del_tramo>
                
                <coordenadas>
                    <longitud valor="7.422222082518584"></longitud>
